version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - 80:80
