version: '3.8'

services:
  backend:
    container_name: backend
    depends_on: 
      - database
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - NODE_API_GOOGLE_API_KEY=$GOOGLE_API_KEY
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - 80:80
    environment:
      - REACT_APP_GOOGLE_API_KEY=$GOOGLE_API_KEY

  database:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
